name: "CI Build Docker Image"

on:
    push:
        branches:
            - main
            - test/cicd
        paths:
          - '02_app/**'

    pull_request:
        branches:
            - main
            - test/cicd
        paths:
          - '02_app/**'

jobs:
    docker-build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v4


            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Extract metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: itmanbuildsclouds/rockpapergame
                tags: |
                  type=ref,event=branch
                  type=ref,event=pr
                  type=sha,prefix={{branch}}-
                  type=raw,value=latest,enable={{is_default_branch}}
                  type=raw,value=${{ github.run_number }}
                  
            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_HUB_NAME }}
                password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Build Docker Image
              uses: docker/build-push-action@v5
              with:
                push: true
                context: ./02_app
                platforms: linux/amd64
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                cache-from: type=gha
                cache-to: type=gha,mode=max

            - name: Log out from Docker Hub
              if: always()
              run: docker logout

            - name: Build summary
              if: success()
              run: |
                echo "Build completed successsfully"
                if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]]; then
                  echo "Image pushed to Docker Hub"
                  echo "Available tags:"
                  echo "${{ steps.meta.outputs.tags }}"
                else
                  echo "Image built locally - no push"
                fi
